### ISSUE TITLE
Cannot install jquery

### ISSUE THREAD

**Issue by dlinov** [truerss/truerss#36]
`install` task produces error when installing jQuery

```
> install
Download jquery-2.1.4.min.js
Exception in thread "Thread-12" javax.net.ssl.SSLHandshakeException: Received fatal alert: handshake_failure
```

workaround is to use http instead of https in jQuery link.

**Comment by fntz** [comment]
https://github.com/truerss/truerss/commit/51899945193a5ebb364ffed5297fa767f824656d

**Comment by dlinov** [comment]
Can't reproduce this issue anymore, why did you reopen it?
