### ISSUE TITLE
Enable feeds auto-update

### ISSUE THREAD

**Issue by dlinov** [truerss/truerss#37]
If site updates in background it would be convenient to use it on TVs

**Comment by fntz** [comment]
can you please remind me about it issue? 
what is TVs? and how it should works?

**Comment by dlinov** [comment]
By TVs I mean large flat LCD panels (including monitors). It should work this way: you open feeds page and it just updates automatically, you don't need touch or click anything.

**Comment by fntz** [comment]
ok

**Comment by fntz** [comment]
https://github.com/truerss/truerss/commit/2eb4d0935e6c7678e8481c07a22d961c10a481a0
