### ISSUE TITLE
check that url is rss 

### ISSUE THREAD

**Issue by fntz** [truerss/truerss#38]

**Comment by dlinov** [comment]
How strict should it be? Should service fetch url and check its content?

**Comment by fntz** [comment]
yep, 
1. check that `atom/xml` content-type
2. otherwise check that application have plugin for this url (not default plugin) or bad request

**Comment by dlinov** [comment]
See http://news.tut.by/rss/all.rss - Content-Type is "application/rss+xml; charset=utf8". Is it also a valid option?

**Comment by fntz** [comment]
yep, `atom/xml` is a just example. i think any content type with `?/?+xml` is a valid option.

**Comment by fntz** [comment]
https://github.com/truerss/truerss/pull/72
